# Use Node.js as the base image
FROM node:16

# Set the working directory
FROM node:16 AS frontend
WORKDIR /frontend

# Copy package.json and install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy the app source code
COPY frontend .

# Build the app
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Command to start the app
CMD ["npm", "start"]
