# Use Miniconda as the base image
FROM continuumio/miniconda3

# Set the working directory
WORKDIR /backend

# Copy environment.yml and install dependencies
COPY backend/environment.yml .
RUN conda env create -f environment.yml

# Set the environment path for Flask to run in the container
ENV PATH /opt/conda/envs/fluid/bin:$PATH
SHELL ["conda", "run", "-n", "fluid", "/bin/bash", "-c"]

# # Copy the backend code into the container
# COPY backend .
COPY backend .

# Expose the port Flask will run on
EXPOSE 5000

# Command to start the Flask app
# CMD ["python", "app.py"]
CMD ["conda", "run", "-n", "fluid", "python", "app.py"]
