name: fluid
channels:
  - conda-forge
dependencies:
  - python
  - flask
  - basemap
  - kerchunk
  - pyyaml
  - libnetcdf
  - gunicorn
  - xlsxwriter
  - cartopy
  - flask-wtf
  - openpyxl
  - fastparquet

