name: fluid
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - basemap=1.4.1
  - kerchunk=0.2.6
  - pyyaml=6.0.2
  - libnetcdf=4.9.2
  - gunicorn=23.0.0
  - xlsxwriter=3.2.0
  - cartopy=0.24.0
  - flask-wtf=1.2.1
  - openpyxl=3.1.5
  - fastparquet=2024.5.0
